
FROM node:20


# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the React application


# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "run","dev"]